# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  tags: [web]
  cache:
    # 缓存nodemodules
    paths:
    - node_modules/
  script:
  - npm install
  - npm run build
  - mkdir .public
  - mv dist/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master

